import React from 'react'
import type { Metadata } from "next";

// Metadata, it'll be shown in browser's tab
export const metadata: Metadata = {
  title: "Blogs - Glow Scout",
  description: "Generated by create next app",
};

export default function Blogs() {
  return (
    <div className="text-4xl flex justify-center items-center my-10">Blogs</div>
  )
}
