import React from 'react';
import Wrapper from '@/components/reusable/Wrapper';
import TreatmentsClient from './components/TreatmentsClient';
import { get_treatments } from '@/lib/api_functions';
import { TreatmentDataType } from '@/lib/types'; 
import type { Metadata } from "next";

// Metadata, it'll be shown in browser's tab
export const metadata: Metadata = {
  title: "Treatments - Glow Scout",
  description: "Generated by create next app",
};

// This is a next.js server component and out tretaments page, it'll list down all treatments
export default async function Treatments() {
  // Here we're calling a function to hit the API to get all treatments
  const filteredData: TreatmentDataType[] | undefined = await get_treatments();

  return (
    <main className="border-t-2 border-t-secondary">
      <Wrapper>
        <TreatmentsClient data={filteredData} />
      </Wrapper>
    </main>
  );
}
