import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

// importing header and footer component to main layout as they'll be consistent for all pages
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

// Initializing font, imported from Google fonts, which will be used in this website
const raleway = Raleway({ subsets: ["latin"] });

// Metadata, it'll be shown in browser's tab
export const metadata: Metadata = {
  title: "Glow Scout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-primary ${raleway.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
