import Wrapper from '@/components/reusable/Wrapper'
import React from 'react'
import Form from './components/Form'

import type { Metadata } from "next";

// Metadata, it'll be shown in browser's tab
export const metadata: Metadata = {
  title: "Book - Glow Scout",
  description: "Generated by create next app",
};

// This is booking page which shows a from to  book an appointment in the desired Spa fro the desired treatment
export default function page() {
  return (
    <main>
        {/* Blurred Divs */}
        <div className="absolute top-36 -right-10 w-96 h-72 bg-trinary rounded-t-full blur-xl -z-10 -rotate-90"></div>
        <div className="absolute top-[35rem] -left-10  w-96 h-72 rounded-t-full bg-trinary blur-xl -z-10 rotate-90"></div>
        <Wrapper>
            <div className="bg-primary flex items-center justify-center">
                <div className="w-full mt-10 p-8 border-[1px] border-secondary rounded-lg shadow-lg">
                    <h2 className="text-4xl text-center font-semibold mb-8">Book Appointment</h2>
                    <Form />
                </div>
            </div>
        </Wrapper>
    </main>
  )
}
